### ISSUE TITLE
Vendor third party packages

### ISSUE THREAD

**Issue by jeffpierce** [jeffpierce/cassabon#104]
We should probably start vendoring the third party packages we use so upstream changes to those packages don't break us...like it has before.

Any arguments against why we shouldn't do this?

**Comment by mredivo** [comment]
I agree, this is a good idea.

There are different ways of doing this, without a clear winner yet. We'll need to survey what's been gaining traction recently.

**Comment by mredivo** [comment]
Finally, sane vendoring: https://golang.org/cmd/go/#hdr-Vendor_Directories

This is the right approach.

**Comment by jeffpierce** [comment]
Cool.  Let's roll with it.

**Comment by jeffpierce** [comment]
Marking as solved.
