### ISSUE TITLE
Detailed documentation please

### ISSUE THREAD

**Issue by utkarshcmu** [jeffpierce/cassabon#105]
Hello Jeff,

It would be great if we can find some more documentation links on cassabon. For details like:
1. Cassandra schema
2. Rollups
3. And elasticsearch details etc.

Thanks !!!

**Comment by jeffpierce** [comment]
Definitely.  Sorry for slacking on that -- I switched to a new company and I've been getting settled in.  I'll make sure to work on that this week/weekend.

**Comment by utkarshcmu** [comment]
Thanks and Congratulations !!!

**Comment by jeffpierce** [comment]
I updated the wiki with a bit more information, especially with the configuration for the YAML file.

Anything else that you'd like to see?

**Comment by utkarshcmu** [comment]
Looks good for now. Will open another issue if need something else. :)
