### ISSUE TITLE
Goroutine Limit 

### ISSUE THREAD

**Issue by utkarshcmu** [jeffpierce/cassabon#108]
When I am posting metrics to Cassabon, it starts indexing in ES but later it dies with the following error:

```
race: limit on 8192 simultaneously alive goroutines is exceeded, dying
exit status 1
```

Is there anything which I am missing in config?

**Comment by jeffpierce** [comment]
Sounds like a ulimit issue with nproc or nofiles.  Increase those and you should be fine.

**Comment by utkarshcmu** [comment]
Does cassabon accepts bulk writes (in plaintext protocol) ?

**Comment by jeffpierce** [comment]
What do you mean by bulk writes?

**Comment by utkarshcmu** [comment]
bulk writes meaning if I write the following stream to cassabon on Port 2003 at once instead of writing each metric one at a time:

```
a.b.c.d 1234567890 34
a.b.c.d 1234567980 35
a.b.c.d 1234564580 35
```

So, will cassabon treat the above input as 3 different metrics?

**Comment by jeffpierce** [comment]
It will, yes.

**Comment by mredivo** [comment]
`race: limit on 8192 simultaneously alive goroutines is exceeded, dying`

Seems to be a built-in limit in Go:
https://github.com/golang/go/issues/6688

I would call this an issue that needs to be addressed in the code.

**Comment by jeffpierce** [comment]
That's...interesting.

All righty then.  Looks like we fix it!

**Comment by utkarshcmu** [comment]
Looks like I was pushing too many metrics to a single cassabon node. When I reduced the number of writes, I am not seeing this error. But we need to fix this.  Looks like in the code somewhere we are not using goroutines optimally.

**Comment by mredivo** [comment]
I think this is the culprit:
https://github.com/jeffpierce/cassabon/blob/master/datastore/indexmanager.go#L83

Need to change this to use bounded parallelism.

**Comment by utkarshcmu** [comment]
I think the same because the DEBUG log lines before the above mentioned error were from IndexManager. The IndexManager tries to index as many metrics as it can and then throws this error like this:

```
2016/04/21 00:00:39.643974 [system] [DEBUG] IndexManager indexing "app"
2016/04/21 00:00:39.645485 [system] [DEBUG] IndexManager indexing "app.prod"
2016/04/21 00:00:39.647396 [system] [DEBUG] IndexManager indexing "app.stage"
2016/04/21 00:00:39.648292 [system] [DEBUG] IndexManager indexing "app.prod"
2016/04/21 00:00:39.650599 [system] [DEBUG] IndexManager indexing "app.prod"
2016/04/21 00:00:39.652640 [system] [DEBUG] IndexManager indexing "app.stage"
2016/04/21 00:00:39.655214 [system] [DEBUG] IndexManager indexing "app"
2016/04/21 00:00:39.657516 [system] [DEBUG] IndexManager indexing "app"
2016/04/21 00:00:39.661016 [system] [DEBUG] IndexManager indexing "app"
race: limit on 8192 simultaneously alive goroutines is exceeded, dying
exit status 1
```

**Comment by mredivo** [comment]
So the trick is to put the load tolerance/elasticity someplace else, where the limit is not low and fixed. I'll study the code and come up with something.

**Comment by jeffpierce** [comment]
I think it's a bit of a thundering herd problem.  Namely, this should really only happen on cassabon restarting -- if it hasn't seen a stat path, it sends it down the indexstore channel.

At that point, it gets looped over, with the full stat being sent to ElasticSearch as a leaf node, then it recursively gets the end popped off and puts that in ES as a branch node.

I could probably store the full tree and short circuit the extra branch writes for branches that IndexManager already knows about.  This would reduce a lot of the load on node/cluster start on the ES server, and that's nearly always the most fragile part of a cassabon node/cluster coming up under load.

Should keep the goroutines from piling up as well.

Thoughts?

**Comment by utkarshcmu** [comment]
+1 for jeff's idea

**Comment by mredivo** [comment]
Good point. When you have 400k paths in normal use, a restart could incur severe traffic to ES.

All paths seen (since restart) are already held in memory, so it would be a shame to duplicate that. We could initialize that map from ElasticSearch data, so that we avoid re-indexing entries that ES already knows about. Relevant code:

https://github.com/jeffpierce/cassabon/blob/master/datastore/metricstore.go#L52

**Comment by jeffpierce** [comment]
Good call.  I'll go down that route.  Should have a PR tonight or tomorrow.

**Comment by jeffpierce** [comment]
@utkarsh In reference to your comment in the pull request, in your cassabon.yaml file, what do you have set as your batchsize under the cassandra settings?

**Comment by utkarshcmu** [comment]
I am using the default "batchsize: 2". I should increase this. :)

**Comment by jeffpierce** [comment]
Yep.  Batchsizes up to 15000 work pretty well.  Try 5000 to start with.

**Comment by jeffpierce** [comment]
Anyway, since this is solved, I'm closing it out.  I'm also updating the wiki to get more docs in there.

**Comment by utkarshcmu** [comment]
Thanks for getting this issue resolved. Looking forward to use Cassabon. 👍
