### ISSUE TITLE
Report Cassabon events to StatsD

### ISSUE THREAD

**Issue by mredivo** [jeffpierce/cassabon#61]
Processing events that are of interest to the team monitoring Cassabon's performance should be logged to StatsD. The code should be audited to determine which events are of interest, and then those events should be instrumented with calls to Statsd.

Currently reported:

- UDP/TCP receive failure
- UDP/TCP receive success
- Number of unique paths indexed since startup/last SIGHUP

**Comment by jeffpierce** [comment]
Completed.
