### ISSUE TITLE
API:  Cassabon returns 204 No Content, which graphite-API cannot handle

### ISSUE THREAD

**Issue by jeffpierce** [jeffpierce/cassabon#72]
If a stat query comes back nil, Cassabon will return 204 no content (or an error), which causes graphite API to fail.

May be related to not populating null steps.

**Comment by mredivo** [comment]
I can't find a code path that will return a 204 No Content.

I did fix an error in calculating timeouts, which was causing a timeout 500 error response. Let's see if that reduces or eliminates this issue.

**Comment by mredivo** [comment]
I fixed another error that was causing responses like:

```
{"from":1444931326,"to":1444931626,"step":6,"series":{"foo.bar.baz.average":null,"foo.bar.baz.count":null,"foo.bar.baz.max":null,"foo.bar.baz.min":null,"foo.bar.baz.sum":null}}
```

The fixed code returns this now:

```
{"from":1444931619,"to":1444931919,"step":6,"series":{"foo.bar.baz.average":[],"foo.bar.baz.count":[],"foo.bar.baz.max":[],"foo.bar.baz.min":[],"foo.bar.baz.sum":[]}}
```

**Comment by jeffpierce** [comment]
Okay.  I'll see in tonight's testing if that clears it up -- otherwise, I'll hunt down better info.

**Comment by jeffpierce** [comment]
Looks clear for now.
